package com.example.bizeasy.navigation


import okhttp3.Route


const val ROUTE_REGISTER = "register"
const val ROUTE_LOGIN = "login"
const val ROUTE_SPLASH = "splashscreen"
const val ROUTE_DASHBOARD="dashboardscreen"
const val ROUTE_CYBERSECURITY_TOPICS = "cybersecurity_topics"
const val ROUTE_CYBER_SECURITY_ETHICS_CONTENT = "cybersecurity_ethics_content"
const val ROUTE_NETWORK_SECURITY_CONTENT = "network_security_content"
const val ROUTES_SYSTEM_SECURITY_CONTENT = "system_security_content"
const val ROUTES_PHISHING_FUNDAMENTALS_CONTENT = "phishing_fundamentals_content"
const val ROUTE_DATA_SCIENCE_TOPICS = "data_science_topics"
const val ROUTE_PYTHON_FOR_DATA_SCIENCE_CONTENT = "python_for_data_science_content"
const val ROUTE_DATA_VISUALIZATION_CONTENT = "data_visualization_content"
const val ROUTE_MACHINE_LEARNING_FUNDAMENTALS_CONTENT = "machine_learning_fundamentals_content"
const val ROUTE_DATA_SCIENCE_INTRODUCTION_CONTENT = "data_science_introduction_content"
const val ROUTE_PANDAS_DATA_ANALYSIS_CONTENT = "pandas_data_analysis_content"
const val ROUTE_MIT_TOPICS = "mit_topics"
const val ROUTE_MIT_INTRODUCTION_CONTENT = "mit_introduction_content"
const val ROUTE_MIT_RESEARCH_AREAS_CONTENT = "mit_research_areas_content"
const val ROUTE_MIT_INNOVATIONS_CONTENT = "mit_innovations_content"
const val ROUTE_ANDROID_DEVELOPMENT_TOPICS = "android_development_topics"
const val ROUTE_ANDROID_INTRODUCTION_CONTENT = "android_introduction_content"
const val ROUTE_ANDROID_STUDIO_SETUP_CONTENT = "android_studio_setup_content"
const val ROUTE_ANDROID_BASIC_UI_CONTENT = "android_basic_ui_content"
const val ROUTE_CLOUD_COMPUTING_TOPICS = "cloud_computing_topics"
//const val ROUTE_CLOUD_INTRODUCTION_CONTENT = "cloud_introduction_content"
//const val ROUTE_CLOUD_SERVICE_MODELS_CONTENT = "cloud_service_models_content"

const val ROUTE_SOFTWARE_DEVELOPMENT_TOPICS = "software_development_topics"

const val ROUTE_PROGRAMMING_LANGUAGES_FUNDAMENTALS_CONTENT = "programming_languages_fundamentals_content"
const val ROUTE_DATA_STRUCTURES_ALGORITHMS_CONTENT = "data_structures_algorithms_content"
const val ROUTE_SOFTWARE_DEVELOPMENT_METHODOLOGIES_CONTENT = "software_development_methodologies_content"
const val ROUTE_CREATE_NOTE = "create_note_screen"
const val ROUTE_READ_NOTE = "read_note_screen"
const val ROUTE_DELETE_NOTE = "delete_note/{noteId}"
const val ROUTE_SELECT_NOTE_TO = "select_note_to_update/{topic}"
const val ROUTE_SELECT_NOTE_TO_DELETE = "select_note_to_delete/{topic}"
const val ROUTE_CYBER_SECURITY_SUB_TOPIC = "cyber_security_subtopic"
const val ROUTE_ADD_NOTE = "add_note"
const val ROUTE_UPDATE_NOTE = "update_note/{noteId}"
const val ROUTE_VIEW_NOTE = "view_note/{noteId}"
const val ROUTE_CLOUD_COMPUTING_INTRODUCTION_CONTENT = "cloud_computing_introduction_content"
const val ROUTE_CLOUD_SERVICE_MODELS_SCREEN = "cloud_service_models_screen"
const val ROUTE_MAJOR_CLOUD_PROVIDERS_CONTENT = "major_cloud_providers_content"
const val ROUTE_INTRODUCTION_TO_SOFTWARE_DEVELOPMENT_CONTENT_SCREEN = "software_development_content_screen"
const val ROUTE_BASIC_UI_COMPONENTS_IN_ANDROID_CONTENT_SCREEN= "basic_ui-components_in_android"